version: "3.9"
name: loan_data_etl

services:
  transform:
    build:
      context: ./etl/data-split
    image: loan-etl
    container_name: loan_etl_container
    working_dir: /app
    volumes:
      - data_vol:/mnt/data # raw input data (mounted from host)
      - object_vol:/mnt/object # processed output
    command: >
      sh -c '
      echo "Waiting for raw data file to be ready..." &&
      until [ -f /mnt/data/raw/accepted_2007_to_2018Q4.csv ]; do
        echo "File not yet available, waiting 5 seconds..." &&
        sleep 5
      done &&
      echo "✅ Raw data file is ready, starting transformation..." &&
      python data-split.py
      '

  rclone_upload:
    image: rclone/rclone:latest
    container_name: rclone_upload_container
    depends_on:
      - transform
    environment:
      - RCLONE_CONFIG=/config/rclone/rclone.conf
    volumes:
      - object_vol:/mnt/object
      - ~/.config/rclone:/config/rclone:ro
    entrypoint: >
      sh -c "
      echo 'Waiting for split data to appear in /mnt/object/loan-default-data/train/train.csv...' &&
      until [ -f /mnt/object/loan-default-data/train/train.csv ]; do
        echo 'Split data not ready, waiting 5 seconds...' &&
        sleep 5
      done &&
      echo '✅ Split data is ready in /mnt/object/loan-default-data. Ready for next pipeline step.'
      "
