version: "3.8"

volumes:
  data_vol:
  object_vol:

services:
  extract:
    container_name: etl_extract_data
    image: python:3.11
    user: root
    volumes:
      - data_vol:/mnt/data
    working_dir: /mnt/data
    command:
      - bash
      - -c
      - |
        set -e
        apt update && apt install -y unzip python3-pip
        pip install gdown

        echo "Resetting raw/ folder..."
        rm -rf /mnt/data/raw
        mkdir -p /mnt/data/raw
        cd /mnt/data/raw

        echo "Downloading dataset zip from Google Drive..."
        gdown --fuzzy 'https://drive.google.com/file/d/12RwwHXdXDp2a0D-NoBxmnXlRLrSI7-wI/view?usp=sharing' -O accepted_2007_to_2018Q4.csv.gz

        echo "Unzipping..."
        gunzip -f accepted_2007_to_2018Q4.csv.gz

        echo "Contents of raw/ directory:"
        ls -lh /mnt/data/raw

  transform:
    build:
      context: ./etl/data-split
    image: loan-etl
    container_name: loan_etl_container
    depends_on:
      - extract
    working_dir: /app
    volumes:
      - data_vol:/mnt/data
      - object_vol:/mnt/object
    command: >
      sh -c '
      echo "Waiting for raw data file to be ready..." &&
      until [ -f /mnt/data/raw/accepted_2007_to_2018Q4.csv ]; do
        echo "File not yet available, waiting 5 seconds..." &&
        sleep 5
      done &&
      echo "Raw data file is ready, starting transformation..." &&
      python data-split.py
      '

  rclone_upload:
    image: rclone/rclone:latest
    container_name: rclone_upload_container
    depends_on:
      - transform
    environment:
      - RCLONE_CONFIG=/config/rclone/rclone.conf
    volumes:
      - object_vol:/mnt/object
      - ~/.config/rclone:/config/rclone:ro
    entrypoint: >
      sh -c "
      echo 'Waiting for cleaned_data.csv...' &&
      until [ -f /mnt/object/loan-default-data/cleaned_data.csv ]; do
        echo 'Cleaned data not ready, waiting 5 seconds...' &&
        sleep 5
      done &&
      echo '✅ Cleaned and split data is ready in /mnt/object/loan-default-data (no copy needed).'
      "
