services:

  fastapi_server:
    build:
      context: ../fastapi_pt
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8001:8000"
    volumes:
      - ./model.pth:/app/model.pth
      - /mnt/object:/mnt/object
      - /mnt/block:/mnt/block
    networks:
      - eval_net
      - persist_block_default
    # depends_on:
    #   - minio-create-prod-bucket


  flask:
    build:
      context: ../../../flask
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      - FASTAPI_SERVER_URL=http://fastapi_server:8000
      - MINIO_URL=http://minio:9000
      - MINIO_USER=your-access-key
      - MINIO_PASSWORD=your-secret-key
    depends_on:
      - fastapi_server
      - minio-create-prod-bucket
    volumes:
      - /mnt/object:/mnt/object
      - /mnt/block:/mnt/block
    networks:
      - eval_net
      - persist_block_default

  minio-create-prod-bucket:
    image: minio/mc
    depends_on:
      - fastapi_server
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 your-access-key your-secret-key &&
      if ! mc ls minio/production-artifacts; then
        mc mb minio/production-artifacts &&
        echo 'Bucket production-artifacts created';
      else
        echo 'Bucket production-artifacts already exists';
      fi"
    networks:
      - persist_block_default

  airflow-webserver:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow-webserver
    entrypoint: /bin/bash
    command: >
      -c "exec airflow webserver"
    ports:
      - "8081:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/mlflowdb
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=some-secret
      - MINIO_URL=http://minio:9000
      - MINIO_USER=your-access-key
      - MINIO_PASSWORD=your-secret-key
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/dags/scripts
      - airflow_shared:/opt/airflow
      - /mnt/object:/mnt/object
      - /mnt/block:/mnt/block
    depends_on:
      airflow-setup:
        condition: service_completed_successfully
    networks:
      - eval_net
      - persist_block_default

  airflow-scheduler:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow-scheduler
    entrypoint: /bin/bash
    command: >
      -c "exec airflow scheduler"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - MINIO_URL=http://minio:9000
      - MINIO_USER=your-access-key
      - MINIO_PASSWORD=your-secret-key
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/dags/scripts
      - airflow_shared:/opt/airflow
      - /mnt/object:/mnt/object
      - /mnt/block:/mnt/block
    depends_on:
      airflow-setup:
        condition: service_completed_successfully
    networks:
      - eval_net
      - persist_block_default

  airflow-setup:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow-setup
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate &&
          airflow users create --username admin --firstname Airflow --lastname Admin --role Admin --email airflow@example.com --password airflow"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/dags/scripts
      - airflow_shared:/opt/airflow
      - /mnt/object:/mnt/object
      - /mnt/block:/mnt/block
    networks:
      - eval_net
      - persist_block_default
    restart: "no"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "0.0.0.0:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/object:/mnt/object
      - /mnt/block:/mnt/block
    networks:
      - eval_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://129.114.25.120:3000
      - GF_SERVER_DOMAIN=129.114.25.120
    depends_on:
      - prometheus
    volumes:
      - /mnt/object:/mnt/object
      - /mnt/block:/mnt/block
    networks:
      - eval_net

volumes:
  airflow_shared:

networks:
  eval_net:
    driver: bridge
  persist_block_default:
    external: true
