services:

  # FastAPI model inference service
  # fastapi_server:
  #   build:
  #     context: ../fastapi_pt
  #     dockerfile: Dockerfile
  #   container_name: fastapi_server
  #   ports:
  #     - "8000:8000"
  #   # depends_on:
  #   #   - minio

  # Flask front-end app
  # flask:
  #   build:
  #     context: ../../../flask_app
  #     dockerfile: Dockerfile
  #   container_name: flask
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FASTAPI_SERVER_URL=http://fastapi_server:8000
  #     - MINIO_URL=http://minio:9000
  #     - MINIO_USER=your-access-key
  #     - MINIO_PASSWORD=your-secret-key
  #   depends_on:
  #     - fastapi_server
  #     #- minio
  #   networks:
  #     - eval_net

  # MinIO object store
  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     - MINIO_ROOT_USER=your-access-key
  #     - MINIO_ROOT_PASSWORD=your-secret-key
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio_data:/data
  #   networks:
  #     - eval_net

  # Sidecar to create the MinIO bucket
  # minio-init:
  #   image: minio/mc
  #   container_name: minio_init
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     sleep 5 &&
  #     mc alias set myminio http://minio:9000 your-access-key your-secret-key &&
  #     mc mb -p myminio/production || echo 'Bucket already exists'
  #     "
  #   networks:
  #     - eval_net

  # Prometheus monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "0.0.0.0:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # networks:
    #   - eval_net

  # Grafana dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://129.114.25.120:3000  # Replace with your actual IP
      - GF_SERVER_DOMAIN=129.114.25.120
    # depends_on:
    #   - prometheus
    # networks:
    #   - eval_net

  # Jupyter notebook for evaluation and drift detection
  # jupyter:
  #   image: quay.io/jupyter/pytorch-notebook:pytorch-2.5.1
  #   container_name: jupyter
  #   ports:
  #     - "8888:8888"
  #   shm_size: 8g
  #   environment:
  #    - LOAN_DATA_DIR=/mnt/obj/loan-default-data
  #   volumes:
  #     - ~/loanradar:/home/kvm
  #     - /mnt/block/loanradar:/mnt/obj
  #   command: >
  #     bash -c "pip install mlflow && start-notebook.sh"
  #   networks:
  #     - eval_net

  # Airflow for feedback loop orchestration
#   airflow-webserver:
#     image: apache/airflow:2.9.3-python3.11
#     container_name: airflow-webserver
#     ports:
#       - "8081:8080"
#     entrypoint: /bin/bash
#     command: -c "exec airflow webserver"
#     environment:
#       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#       - AIRFLOW__CORE__FERNET_KEY=your-fernet-key
#       - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
#       - AIRFLOW__CORE__LOAD_EXAMPLES=False
#       - MINIO_URL=http://minio:9000
#       - MINIO_USER=your-access-key
#       - MINIO_PASSWORD=your-secret-key
#     depends_on:
#       airflow-setup:
#         condition: service_completed_successfully
#     volumes:
#       - /home/cc/eval-chi/dags:/opt/airflow/dags
#       - airflow_shared:/opt/airflow
#     networks:
#       - eval_net

#   airflow-scheduler:
#     image: apache/airflow:2.9.3-python3.11
#     container_name: airflow-scheduler
#     entrypoint: /bin/bash
#     command: -c "exec airflow scheduler"
#     environment:
#       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#       - AIRFLOW__CORE__FERNET_KEY=your-fernet-key
#       - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
#       - AIRFLOW__CORE__LOAD_EXAMPLES=False
#       - LABEL_STUDIO_URL=http://label-studio:8080
#       - LABEL_STUDIO_USER_TOKEN=your-label-token
#       - MINIO_URL=http://minio:9000
#       - MINIO_USER=your-access-key
#       - MINIO_PASSWORD=your-secret-key
#     depends_on:
#       airflow-setup:
#         condition: service_completed_successfully
#     volumes:
#       - /home/cc/eval-chi/dags:/opt/airflow/dags
#       - airflow_shared:/opt/airflow
#     networks:
#       - eval_net

#   airflow-setup:
#     image: apache/airflow:2.9.3-python3.11
#     container_name: airflow-setup
#     entrypoint: /bin/bash
#     command: -c "airflow db migrate && airflow users create --username admin --firstname Airflow --lastname Admin --role Admin --email airflow@example.com --password airflow"
#     environment:
#       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#       - AIRFLOW__CORE__FERNET_KEY=your-fernet-key
#       - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
#       - AIRFLOW__CORE__LOAD_EXAMPLES=False
#     volumes:
#       - /home/cc/eval-chi/dags:/opt/airflow/dags
#       - airflow_shared:/opt/airflow
#     networks:
#       - eval_net

#   # Postgres DB for Airflow
#   postgres:
#     image: postgres:latest
#     container_name: postgres
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - eval_net

# volumes:
#   minio_data:
  # food11:
  #   external: true
  # airflow_shared:
  # postgres_data:

networks:
  eval_net:
    driver: bridge
